version: '2.1'

services:    
  kong1:
    image: kong:latest
    volumes:
      - ./declarative:/usr/local/kong/declarative
    environment:    
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
  
    mem_limit: "3g"
    memswap_limit: "3g"
    cpus: 4
    logging:
      options:
        max-size: "50m"
    networks:
      - kong-net
    restart: always


  kong2:
    image: kong:latest
    volumes:
      - ./declarative:/usr/local/kong/declarative
    environment:    
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
  
    mem_limit: "3g"
    memswap_limit: "3g"
    cpus: 4
    logging:
      options:
        max-size: "50m"
    networks:
      - kong-net
    restart: always
       
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/nginx-logs
    ports:
      - "8080:8080"
   
    mem_limit: "2g"
    memswap_limit: "2g"
    cpus: 4
    logging:
      options:
        max-size: "50m"
    networks:
      - kong-net
    restart: always

networks:
  kong-net:
    driver: bridge
   